# Title of the page
title: "El Fracasorium"
# Your name
author: Israel Aguilar
# Show a link to LinkedIn in the header intro. Comment out to disable.
linkedin: https://www.linkedin.com/in/iaguilaror/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
#  url: https://neil.gg
  title: iaguilaror.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - October 1987: "👶 Nací en Pueblita de Los Ángeles"
    - October 1997: "Por primera vez le pedí a una niña que fuera mi novia, y dijo que sí (Saludos Wen). En mi cabeza, todo en la vída iba a salir a mi favor después de eso :)"    
  - name: 2000's
    events:
    - Julio 2000: "Ocurre el primero de mis fracasos amorosos; oh, el drama"
    - Abril 2001: "Me llevan a un concurso de cuento de la secundaría con la promesa de que se podrá escribir a computadora. Pero mintieron. Spoiler: mi letra estaba muy culera así que no me dio tiempo de escribir mucho, y terminé plagiando un episodio de Mujer Casos de la Vida Real"
    - Julio 2004: "Me rechazan en mi primer intento de entrar a la Universidad (tenía un promedio muy malo comparado con los otros aspirantes. Pero qué quieren, me gustaba ir al billar...); eventualmente entraría"
  - name: 2010's
    events:
    - Septiembre 2011: "Me aceptan en la Maestría en CBQ :) ¿En serio te pagan por estudiar?"
    - Septiembre 2013: "Se me acaba la beca de Maestría y yo no tengo ni un pinche experimento exitoso. También se me agotaron las ganas de ir al lab diario, y todo se volvió una espiral horrible hacia la decadencia. Se bebió. Mucho."
    - Abril 2015: "Mi jefe me dice que si sigo sin titularme voy a ser un investigador mediocre. Yo me ardo, y me regreso a Puebla a escribir mi tesis en un mes"
    - Agosto 2015: "Por fin me titulo de maestría (después de 4 años grises). Señoooor... me has mirado a los ojos... Sonriendo..."
    - Septiembre 2015: "Conozco la Bioinformática y mi vida cambia :)"
    - Julio 2016: "Me rechazan del ingreso a doctorado en CBQ porque no preparé bien mi proyecto. Llegué muy b*rguitz, y el proyecto era un desastre"
    - Julio 2017: "Me preparé durante un año y por fin me aceptan en el doctorado"
  - name: 2020's
    events:
    - February 2020: "Me rechazan el paper del doctorado en PNAS, Natcoms y PLOS Genetics. Razón: muy descriptivo el trabajo. Okey."
    - Enero 2020: "Se titula Judith, mi primer alumna de licenciatura!"
    - Febrero 2020: "Se crea BioFreelancer"
    - Agosto 2020: "También se titula Ram!"
    - October 2020: "Se da el primer Curso BioFreelancer: Linux para Principiantes :)"
    - Diciembre 2020: "Nos rechazan un proyecto de Vigilancia Patogenómica en alguna convocatoria Conacyt. Razón: Quién eres tú chamaco para creer que puedes analizar la dinámica de la infección a partir de datos públicos?"
    - April 2021: "Después de un año de trabajo a marchas forzadas, por fin ACEPTAN el paper del doctorado!"
    - Enero 2022: "Zai y yo nos vamos a vivir juntos ya forevar :)"
    - Enero 2022: "Compramos nuestro primer carrito"
    - Marzo 2022: "Rechazan mi aplicación como Nextflow Software Advocate en LatAm. Esta era una chamba que quería con muchas, muchas ganas"
    - Marzo 2022: "Inicio este Fracasorium como recordarotio de que no todo sale a mi favor. Pero aquí seguimos"
    - Octubre 2022: "Me rechazaron de una aplicación para posdoc con David Reich. También yo me la mamé, tirándo a las estrellas :)"
    - Octubre 2022: "Me rechazaron mi tesis en el último voto de sinodal. La razón: me falta entender el contexto social de lo que estudio"
    - Noviembre 2022: "Me rechazaron de una aplicación para posdoc en el EVA Max Planck: Razón: no sé, no me dijeron"
    - Mayo 2023: "Hago mi examen después de 6 meses de retrabajar la tesis. Spoiler: el sinodal que me pidió retrabajar la tesis no fue a mi examen..."
    - Mayo 2023: "Por fin me titulé, y no es fracaso pero sí por qué.."
    - Marzo 2023: "Estamos esperando un Bbx!"
    - Junio 2023: "Me rechazaron del SNI porque no me valen el Acta de Examen como comprobante de grado"
    - Junio 2023: "Ahora tengo que esperar año y medio para ser SNI. Cámara no me agüito"
    - Julio 2023: "Zai y yo conseguimos un depa a la vuelta de donde trabajo. Por fin!"
    
